# -*- coding: utf-8 -*-
"""Student Performance Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qu2e5JIhpRQkSXOHL1m7KFy_LHHmzYbJ

# Data Set Up

Libraries importation
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

"""Set the Record Count"""

np.random.seed(42)
n_students=100

"""Generation the input features (X)"""

study_hours=np.round(np.random.uniform(0,10,n_students),1)
attendance=np.random.randint(50, 100, n_students)
previous_grade=np.random.randint(0,100,n_students)

"""Creating the Target Variable"""

noise=np.random.normal(loc=0, scale=4, size=n_students)
weighted_score=(study_hours*5)+(attendance*0.3)+(previous_grade*0.2)

"""Final Grade"""

final_grade=np.clip(weighted_score+noise, 0,100).astype(int)

"""# Creating the data frame"""

data=pd.DataFrame({
    "study_hours":study_hours,
    "attendance": attendance,
    "previous_grade":previous_grade,
    "final_grade":final_grade
    })
data.to_csv('student_data.csv', index=False)
print(data.head())
data.describe()

print(data.corr(),"\n")
pd.set_option('display.max_rows', None)
print(data)

"""Correlation Visualisation"""

sns.heatmap(data.corr(), annot=True)

"""# Building the model"""

X=data.drop('final_grade',axis=1)
Y=data['final_grade']

X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.3, random_state=0)

"""Train The Model"""

model=RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, Y_train)

"""# Making Predictions"""

Y_pred=model.predict(X_test)
r2=r2_score(Y_test,Y_pred)

print(f"Model accuracy(R2 score){r2*100:.2f}%")

"""# Visualisation"""

prediction_df=pd.DataFrame({
    "Actual Grade": Y_test.values,
    "Predicted Grade": Y_pred
})
print('Actual vs. Predicted Grades')
print(prediction_df.head())

plt.figure(figsize=(7, 7))

sns.scatterplot(x='Actual Grade', y='Predicted Grade', data=prediction_df)
plt.title('Random Forest: Predicted Grades vs. Actual Grades')
plt.xlabel('Actual Final Grade (y_test)')

min_val = min(prediction_df['Actual Grade'].min(), prediction_df['Predicted Grade'].min())
max_val = max(prediction_df['Actual Grade'].max(), prediction_df['Predicted Grade'].max())

plt.plot([min_val, max_val], [min_val, max_val], color='red', linestyle='--', linewidth=2, label='Perfect Fit')
plt.ylabel('Predicted Final Grade (y_pred)')
plt.legend()
plt.grid(True, alpha=0.4)
plt.show()